# -*- coding: utf-8 -*-
"""mk_f.py SRC_DIR OUT_DIR -- the _f study set from the z7 scripts in SRC_DIR.

_f = the MIT study with the new plant built on the EXISTING MPTs
(NEW_PLANT["connect"] = "egf_mpt"): one new feeder per existing feeder, each
landing on the MPT low-side bus that feeder already uses -- no new MPT, no new
tie. Everything else is the z7 study unchanged.

So an _f run never touches a normal run, everything it writes is named apart:
    results_base_f / results_proj_f        (normal: results_base / results_proj)
    <case>_f[...].cnl/.cnv/.snp/.sav        (normal: <case>[...])
    comparison_f, comparison_scenarios_f, comparison_pairs_f
    LIVE_STATUS_f*, SWEEP_PLAN_f*, .spp_slots_f_*, .spp_alive_f_*, .spp_scoring_busy_f
and each _f script starts the other _f scripts, never the normal ones.

Run again whenever the z7 scripts change: python3 mk_f.py <z7 folder> <out folder>."""
import os
import re
import sys

FILES = ["z7_main.py", "z7_lch_b.py", "z7_lch_p.py", "z7_spp_b.py", "z7_spp_p.py", "z7_cmp_multi.py"]


BANNER = ('# ============================================================================\n'
          '#  _f VERSION -- the new plant built on the EXISTING MPTs\n'
          '#  (NEW_PLANT["connect"] = "egf_mpt"): one new feeder per existing feeder,\n'
          '#  on the MPT low-side bus that feeder uses. No new MPT, no new tie.\n'
          '#  Writes ONLY to *_f names, so it never touches a normal run.\n'
          '#  Generated by z7_f/mk_f.py from %s -- edit the z7 scripts, not this.\n'
          '# ============================================================================\n')


def sub(txt, old, new, n, what):
    k = txt.count(old)
    if k != n:
        raise SystemExit("%s: expected %d of %r, found %d" % (what, n, old[:70], k))
    return txt.replace(old, new)


def rename(txt):
    txt = re.sub(r"\bz7_(main|spp_b|spp_p|lch_b|lch_p|cmp_multi)\.py", r"z7_\1_f.py", txt)
    return txt


def engine(txt, f):
    txt = sub(txt, '_plain = os.path.join(STUDY_DIR, "results")', '_plain = os.path.join(STUDY_DIR, "results_f")', 1, f)
    txt = sub(txt, '"results_%s" % _RES_KIND', '"results_%s_f" % _RES_KIND', 1, f)
    txt = sub(txt, "\n    CASE_TAG = _TAG_ROOT\n",
              "\n    CASE_TAG = _TAG_ROOT\nCASE_TAG += \"_f\"     # _f: its own .sav/.cnl/.cnv/.snp beside the normal ones\n", 1, f)
    txt = sub(txt, 'tagp = (RUN_PROJECT or "study").replace(" ", "_")',
              'tagp = "F_" + (RUN_PROJECT or "study").replace(" ", "_")', 1, f)
    return txt


def connect_mpt(txt, f):
    """_f: the new plant on the existing MPTs."""
    return sub(txt, '    "connect":   "poi",', '    "connect":   "egf_mpt",', 1, f)


def launcher(txt, f):
    # EVERY PROJECT RUNS: one that fails is reported and the queue goes on
    # (the _Q run stopped at EmpirePrairie and never started EastFork).
    txt = sub(txt, "\nSTOP_ON_FAILED_PROJECT = True", "\nSTOP_ON_FAILED_PROJECT = False", 1, f)
    txt = sub(txt, '_plain = os.path.join(STUDY_DIR, "results")', '_plain = os.path.join(STUDY_DIR, "results_f")', 1, f)
    txt = sub(txt, '"results_%s" % _RES_KIND', '"results_%s_f" % _RES_KIND', 1, f)
    return txt


def main_panel(txt, f):
    txt = sub(txt, 'return os.path.join(d, "results")', 'return os.path.join(d, "results_f")', 1, f)
    txt = sub(txt, '_old = os.path.join(d, "results")', '_old = os.path.join(d, "results_f")', 1, f)
    txt = sub(txt, '"results_%s" % str(case.get("key") or "").lower()',
              '"results_%s_f" % str(case.get("key") or "").lower()', 1, f)
    txt = re.sub(r'^CMP_FOLDER = "comparison"', 'CMP_FOLDER = "comparison_f"', txt, count=1, flags=re.M)
    txt = re.sub(r'^SCEN_CMP_FOLDER = "comparison_scenarios"', 'SCEN_CMP_FOLDER = "comparison_scenarios_f"',
                 txt, count=1, flags=re.M)
    if 'CMP_FOLDER = "comparison_f"' not in txt or 'SCEN_CMP_FOLDER = "comparison_scenarios_f"' not in txt:
        raise SystemExit("%s: CMP_FOLDER / SCEN_CMP_FOLDER not found" % f)
    txt = sub(txt, '_case_dir(CMP_FOLDER, "comparison")', '_case_dir(CMP_FOLDER, "comparison_f")', 1, f)
    txt = sub(txt, '_case_dir(SCEN_CMP_FOLDER, "comparison_scenarios")',
              '_case_dir(SCEN_CMP_FOLDER, "comparison_scenarios_f")', 1, f)
    # THE PANEL'S OWN STATUS AND CORE-SHARING FILES in the study root: each
    # panel clears its slot files when it starts, so sharing them would let a
    # _f launch wipe a normal launch's worker counts (and the other way round).
    txt = sub(txt, '".spp_slots_%s.txt"', '".spp_slots_f_%s.txt"', 1, f)
    txt = sub(txt, '".spp_alive_%s.txt"', '".spp_alive_f_%s.txt"', 1, f)
    txt = sub(txt, '".spp_scoring_busy.txt"', '".spp_scoring_busy_f.txt"', 1, f)
    txt = re.sub(r'^SWEEP_PLAN_FILE = "SWEEP_PLAN.txt"', 'SWEEP_PLAN_FILE = "SWEEP_PLAN_f.txt"', txt, count=1, flags=re.M)
    txt = re.sub(r'^LIVE_STATUS_ALL = "LIVE_STATUS.txt"', 'LIVE_STATUS_ALL = "LIVE_STATUS_f.txt"', txt, count=1, flags=re.M)
    if 'SWEEP_PLAN_FILE = "SWEEP_PLAN_f.txt"' not in txt or 'LIVE_STATUS_ALL = "LIVE_STATUS_f.txt"' not in txt:
        raise SystemExit("%s: SWEEP_PLAN_FILE / LIVE_STATUS_ALL not found" % f)
    return txt


def cmp_multi(txt, f):
    txt = sub(txt, '"z7_spp_%s.py" % kind', '"z7_spp_%s_f.py" % kind', 1, f)
    txt = sub(txt, '_STD_PARENTS = ("results_base", "results_proj",',
              '_STD_PARENTS = ("results_base_f", "results_proj_f", "results_base", "results_proj",', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Base", "results_base")',
              'os.path.join(z4.STUDY_ROOT, "Base", "results_base_f")', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Projects", "results_proj")',
              'os.path.join(z4.STUDY_ROOT, "Projects", "results_proj_f")', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Base", "results_base*")',
              'os.path.join(z4.STUDY_ROOT, "Base", "results_base_f*")', 1, f)
    # the normal tool leaves the _f folders out of its scenario search; this one
    # searches ONLY them, so that filter goes
    txt = sub(txt, ' and not os.path.basename(d).lower().endswith(("_q", "_f"))', '', 1, f)
    txt = sub(txt, "        # NOT THE _Q STUDY'S (results_base_q): the queue-project runs have their\n"
                   "        # own panel and side-by-side, and are not scenarios of this study.\n",
              "        # _f: ONLY this study's own base runs (results_base_f*).\n", 1, f)
    txt = sub(txt, 'if parent not in ("results_base", "results_proj"):',
              'if parent not in ("results_base_f", "results_proj_f"):', 1, f)
    txt = sub(txt, '%s\\\\results_%s\\\\%s\\\\%s, not to this folder', '%s\\\\results_%s_f\\\\%s\\\\%s, not to this folder', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "comparison_pairs")',
              'os.path.join(z4.STUDY_ROOT, "comparison_pairs_f")', 4, f)
    return txt


def main():
    src, out = sys.argv[1], sys.argv[2]
    if not os.path.isdir(out):
        os.makedirs(out)
    for f in FILES:
        with open(os.path.join(src, f), encoding="utf-8") as fh:
            txt = fh.read()
        if "_spp_" in f:
            txt = engine(txt, f)
            if f == "z7_spp_p.py":
                txt = connect_mpt(txt, f)
        elif "_lch_" in f:
            txt = launcher(txt, f)
        elif f == "z7_main.py":
            txt = main_panel(txt, f)
            txt = connect_mpt(txt, f)
        elif f == "z7_cmp_multi.py":
            txt = cmp_multi(txt, f)
        txt = rename(txt)
        # banner after the coding line / shebang
        lines = txt.split("\n")
        k = 1 if lines and lines[0].startswith("#") and "coding" in lines[0] else 0
        lines.insert(k, BANNER.rstrip("\n") % f)
        dst = os.path.join(out, f.replace(".py", "_f.py"))
        with open(dst, "w", encoding="utf-8", newline="") as fh:
            fh.write("\n".join(lines))
        print("wrote %s" % dst)


if __name__ == "__main__":
    main()
