# -*- coding: utf-8 -*-
"""mk_q.py SRC_DIR OUT_DIR -- the _Q study set from the z7 scripts in SRC_DIR.

_Q = the same study, the same .sav and .dyr, PLUS the dynamic-data decks of the
queue projects in the vicinity: the full @input list of the DIS2301
Run1-create-snap.idv (DyreChanges, AECI, and the 24 "000_*.idv" decks). Every
other build/init step of that .idv is already what the z7 scripts do.

So a _Q run never touches a normal run, everything it writes is named apart:
    results_base_q / results_proj_q        (normal: results_base / results_proj)
    <case>_Q[...].cnl/.cnv/.snp/.sav        (normal: <case>[...])
    LOADED_*_Q_<project>.dyr                (normal: LOADED_*_<project>.dyr)
    comparison_q, comparison_scenarios_q, comparison_pairs_q
    LIVE_STATUS_Q*, SWEEP_PLAN_Q*, .spp_slots_Q_*, .spp_alive_Q_*, .spp_scoring_busy_Q
and each _Q script starts the other _Q scripts, never the normal ones.

Run again whenever the z7 scripts change: python3 mk_q.py <z7 folder> <out folder>."""
import os
import re
import sys

FILES = ["z7_main.py", "z7_lch_b.py", "z7_lch_p.py", "z7_spp_b.py", "z7_spp_p.py", "z7_cmp_multi.py"]

DYRECHANGE_Q = '''DYRECHANGE_IDV = [  # _Q: exactly the @input list of the DIS2301 Run1-create-snap.idv, in order
    "2020MDWG-DS34-RED-FINAL-25S-DyreChanges.idv",
    "AECI_dyr_TRate_changes.idv",
    "000_514646_GE_Pmin.idv",
    "000_GEN-2014-028_WSIEG1_Pmax.idv",
    "000_Disable_532957_WTDTA1.idv",
    "000_Disable_534023_WTDTA1.idv",
    "000_659272_Pmin.idv",
    "000_584713_Trate.idv",
    "000_Disable_WTDTA1.idv",
    # "000_Disable_Protection.idv",          # commented out in the .idv
    "000_GEN-2017-221_PPC.idv",
    "000_GEN-2018-049_PPC.idv",
    "000_GEN-2018-093_PPC.idv",
    "000_GEN-2017-068_PPC.idv",
    "000_Gen-2019-016_PPC.idv",
    "000_ENSIGN_WTG_DISABLE_REAX3BU1.idv",
    "000_GEN-2020-007_PPC.idv",
    "000_GEN-2011-008_PPC.idv",
    "000_GEN-2020-008_PPC.idv",
    "000_GEN-2020-057_PPC.idv",
    "000_GEN-2023-194_PPC.idv",
    "000_GEN-2020-079_PPC.idv",
    "000_GEN-2023-037_PPC.idv",
    "000_GEN-2023-033_PPC.idv",
    "000_GEN-2023-023_PPC.idv",
    "000_GEN-2022-100_PPC.idv",
    "000_GEN-2018-030_PPC.idv",
]   # a deck missing from the study folder is skipped with a [WARN]
'''

BANNER = ('# ============================================================================\n'
          '#  _Q VERSION -- the study WITH the queue projects in the vicinity.\n'
          '#  Same .sav and .dyr as the normal scripts; the build also applies the\n'
          '#  queue decks of the DIS2301 Run1-create-snap.idv (DYRECHANGE_IDV).\n'
          '#  Writes ONLY to *_q / *_Q names, so it never touches a normal run.\n'
          '#  Generated by z7_q/mk_q.py from %s -- edit the z7 scripts, not this.\n'
          '# ============================================================================\n')


def sub(txt, old, new, n, what):
    k = txt.count(old)
    if k != n:
        raise SystemExit("%s: expected %d of %r, found %d" % (what, n, old[:70], k))
    return txt.replace(old, new)


def rename(txt):
    txt = re.sub(r"\bz7_(main|spp_b|spp_p|lch_b|lch_p|cmp_multi)\.py", r"z7_\1_Q.py", txt)
    return txt


def engine(txt, f):
    txt = sub(txt, '_plain = os.path.join(STUDY_DIR, "results")', '_plain = os.path.join(STUDY_DIR, "results_q")', 1, f)
    txt = sub(txt, '"results_%s" % _RES_KIND', '"results_%s_q" % _RES_KIND', 1, f)
    txt = sub(txt, "\n    CASE_TAG = _TAG_ROOT\n",
              "\n    CASE_TAG = _TAG_ROOT\nCASE_TAG += \"_Q\"     # _Q: its own .sav/.cnl/.cnv/.snp beside the normal ones\n", 1, f)
    txt = sub(txt, 'tagp = (RUN_PROJECT or "study").replace(" ", "_")',
              'tagp = "Q_" + (RUN_PROJECT or "study").replace(" ", "_")', 1, f)
    m = re.search(r"^DYRECHANGE_IDV = \[.*?\]\s*(#[^\n]*)?\n", txt, re.S | re.M)
    if not m:
        raise SystemExit("%s: DYRECHANGE_IDV not found" % f)
    txt = txt[:m.start()] + DYRECHANGE_Q + txt[m.end():]
    return txt


def launcher(txt, f):
    txt = sub(txt, '_plain = os.path.join(STUDY_DIR, "results")', '_plain = os.path.join(STUDY_DIR, "results_q")', 1, f)
    txt = sub(txt, '"results_%s" % _RES_KIND', '"results_%s_q" % _RES_KIND', 1, f)
    return txt


def main_panel(txt, f):
    txt = sub(txt, 'return os.path.join(d, "results")', 'return os.path.join(d, "results_q")', 1, f)
    txt = sub(txt, '_old = os.path.join(d, "results")', '_old = os.path.join(d, "results_q")', 1, f)
    txt = sub(txt, '"results_%s" % str(case.get("key") or "").lower()',
              '"results_%s_q" % str(case.get("key") or "").lower()', 1, f)
    txt = re.sub(r'^CMP_FOLDER = "comparison"', 'CMP_FOLDER = "comparison_q"', txt, count=1, flags=re.M)
    txt = re.sub(r'^SCEN_CMP_FOLDER = "comparison_scenarios"', 'SCEN_CMP_FOLDER = "comparison_scenarios_q"',
                 txt, count=1, flags=re.M)
    if 'CMP_FOLDER = "comparison_q"' not in txt or 'SCEN_CMP_FOLDER = "comparison_scenarios_q"' not in txt:
        raise SystemExit("%s: CMP_FOLDER / SCEN_CMP_FOLDER not found" % f)
    txt = sub(txt, '_case_dir(CMP_FOLDER, "comparison")', '_case_dir(CMP_FOLDER, "comparison_q")', 1, f)
    txt = sub(txt, '_case_dir(SCEN_CMP_FOLDER, "comparison_scenarios")',
              '_case_dir(SCEN_CMP_FOLDER, "comparison_scenarios_q")', 1, f)
    # THE PANEL'S OWN STATUS AND CORE-SHARING FILES in the study root: each
    # panel clears its slot files when it starts, so sharing them would let a
    # _Q launch wipe a normal launch's worker counts (and the other way round).
    txt = sub(txt, '".spp_slots_%s.txt"', '".spp_slots_Q_%s.txt"', 1, f)
    txt = sub(txt, '".spp_alive_%s.txt"', '".spp_alive_Q_%s.txt"', 1, f)
    txt = sub(txt, '".spp_scoring_busy.txt"', '".spp_scoring_busy_Q.txt"', 1, f)
    txt = re.sub(r'^SWEEP_PLAN_FILE = "SWEEP_PLAN.txt"', 'SWEEP_PLAN_FILE = "SWEEP_PLAN_Q.txt"', txt, count=1, flags=re.M)
    txt = re.sub(r'^LIVE_STATUS_ALL = "LIVE_STATUS.txt"', 'LIVE_STATUS_ALL = "LIVE_STATUS_Q.txt"', txt, count=1, flags=re.M)
    if 'SWEEP_PLAN_FILE = "SWEEP_PLAN_Q.txt"' not in txt or 'LIVE_STATUS_ALL = "LIVE_STATUS_Q.txt"' not in txt:
        raise SystemExit("%s: SWEEP_PLAN_FILE / LIVE_STATUS_ALL not found" % f)
    return txt


def cmp_multi(txt, f):
    txt = sub(txt, '"z7_spp_%s.py" % kind', '"z7_spp_%s_Q.py" % kind', 1, f)
    txt = sub(txt, '_STD_PARENTS = ("results_base", "results_proj",',
              '_STD_PARENTS = ("results_base_q", "results_proj_q", "results_base", "results_proj",', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Base", "results_base")',
              'os.path.join(z4.STUDY_ROOT, "Base", "results_base_q")', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Projects", "results_proj")',
              'os.path.join(z4.STUDY_ROOT, "Projects", "results_proj_q")', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "Base", "results_base*")',
              'os.path.join(z4.STUDY_ROOT, "Base", "results_base_q*")', 1, f)
    # the normal tool leaves the _q folders out of its scenario search; this one
    # searches ONLY them, so that filter goes
    txt = sub(txt, ' and not os.path.basename(d).lower().endswith("_q")', '', 1, f)
    txt = sub(txt, "        # NOT THE _Q STUDY'S (results_base_q): the queue-project runs have their\n"
                   "        # own panel and side-by-side, and are not scenarios of this study.\n",
              "        # _Q: ONLY the queue study's own base runs (results_base_q*).\n", 1, f)
    txt = sub(txt, 'if parent not in ("results_base", "results_proj"):',
              'if parent not in ("results_base_q", "results_proj_q"):', 1, f)
    txt = sub(txt, '%s\\\\results_%s\\\\%s\\\\%s, not to this folder', '%s\\\\results_%s_q\\\\%s\\\\%s, not to this folder', 1, f)
    txt = sub(txt, 'os.path.join(z4.STUDY_ROOT, "comparison_pairs")',
              'os.path.join(z4.STUDY_ROOT, "comparison_pairs_q")', 4, f)
    return txt


def main():
    src, out = sys.argv[1], sys.argv[2]
    if not os.path.isdir(out):
        os.makedirs(out)
    for f in FILES:
        with open(os.path.join(src, f), encoding="utf-8") as fh:
            txt = fh.read()
        if "_spp_" in f:
            txt = engine(txt, f)
        elif "_lch_" in f:
            txt = launcher(txt, f)
        elif f == "z7_main.py":
            txt = main_panel(txt, f)
        elif f == "z7_cmp_multi.py":
            txt = cmp_multi(txt, f)
        txt = rename(txt)
        # banner after the coding line / shebang
        lines = txt.split("\n")
        k = 1 if lines and lines[0].startswith("#") and "coding" in lines[0] else 0
        lines.insert(k, BANNER.rstrip("\n") % f)
        dst = os.path.join(out, f.replace(".py", "_Q.py"))
        with open(dst, "w", encoding="utf-8", newline="") as fh:
            fh.write("\n".join(lines))
        print("wrote %s" % dst)


if __name__ == "__main__":
    main()
